// Copyright (c) Omlox Client Go Contributors
// SPDX-License-Identifier: MIT
//
// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package omlox

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

//  ProvidersAPI is a simple wrapper around the client for ProvidersAPI 
type ProvidersAPI interface {



















